/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface Order {
  'id' : bigint,
  'service' : string,
  'status' : ReferralStatus,
  'name' : string,
  'whatsapp' : string,
  'message' : string,
  'timestamp' : string,
  'phone' : string,
}
export type ReferralStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface Stats {
  'successRate' : bigint,
  'videosCreated' : bigint,
  'totalClients' : bigint,
}
export interface Testimonial {
  'id' : bigint,
  'service' : string,
  'review' : string,
  'name' : string,
  'approved' : boolean,
  'rating' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestimonial' : ActorMethod<[string, string, bigint, string], bigint>,
  'approveTestimonial' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getApprovedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getOrdersByStatus' : ActorMethod<[ReferralStatus], Array<Order>>,
  'getStats' : ActorMethod<[], Stats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, ReferralStatus], undefined>,
  'updateStats' : ActorMethod<[Stats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];